# Generated by Django 3.0.1 on 2020-04-01 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0003_attend_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 1, 12, 19, 29, 255000)),
        ),
    ]
