# Generated by Django 3.0.1 on 2020-04-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0004_auto_20200401_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
