# Generated by Django 3.0.3 on 2020-04-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0006_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='name',
        ),
    ]
