# Generated by Django 3.0.3 on 2020-04-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0007_remove_attend_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
